### ISSUE TITLE
Future proofing of 50-coredump.conf

### ISSUE THREAD

**Issue by Trucido** [kororaproject/kp-korora-extras#10]
https://github.com/kororaproject/kp-korora-extras/blob/68d20744b111571f43a5dcf20ecdb41bbe282158/build/korora-extras.spec#L66
https://github.com/kororaproject/kp-korora-extras/blob/68d20744b111571f43a5dcf20ecdb41bbe282158/build/korora-extras.spec#L67
  
sorry too tired to fork and pull request or to track down where that file is to issue against it but a better way is overriding 50-coredump.conf with `kernel.core_pattern = |/bin/false` that way future updates won't potentially get srewed up. And yes, before you ask... I read all the F'ing manuals and none gave information on how to disable dumps, and systemd ignores it's own /etc/systemd/* files, as well as kernel cmdline, and ulimits. The below will override /usr/lib/sysctl.d/50-coredump.conf with essentially the same thing as pointing it to /dev/null

Here's my config, though I think suid_dumpable is redundant or unnecessary.  
WARNING: vulgar language:
  

**`/etc/sysctl.d/50-nofuckingdumps.conf`**
```
## ./etc/sysctl.d/50-nofuckingdumps.conf
##					NO DUMP ZONE					##
## No fucking dumping									##
## To any son of a bitch init system that dares dump here without my permission.	##
## You will be fucked-up on site and your remains will be nuked from orbit into the	##
## smoldering pile of trash from which you came.					##
fs.suid_dumpable = 0
kernel.suid_dumpable = 0
kernel.core_pattern = |/bin/false
```

**Comment by jimkp** [comment]
While we appreciate input please refrain from vulgar language. It doesn't help your argument and actually makes more difficult to take it seriously. No future use of profanity will be accepted.

**Comment by firnsy** [comment]
Whilst we appreciate all contributions, I'll have to close this due to no description of the problem, proposed solution and inordinate use of expletives.

**Comment by Trucido** [comment]
Sorry, I often use profanity in my own system files and was exhausted while writing this.  
I just wanted to let you guys know there was a better way of disabling coredumps without modifying existing files belonging to package(s).
  
Problem: the current `/usr/lib/sysctl.d/50-coredump.conf -> /dev/null` has multiple problems; 
1. system verification detects it as invalid, and rpm -V
2. future updates could still change this file
3. future updates could fail entirely due to not being able to install the system file (which comes with systemd).

**/etc/sysctl.d/50-nocoredump.conf**
```
fs.suid_dumpable = 0
kernel.suid_dumpable = 0
kernel.core_pattern = |/bin/false
```
  
Is that better? Also, use `/etc/limits.d/` instead of writing directly to /etc/limits.conf, since that can be overwritten also.
